function normalizeText(value) {
  return value
    .toString()
    .trim()
    .replace(/\s+/g, ' ')
    .toLowerCase();
}

function normalizeStatsFilterValue(value) {
  const raw = value == null ? '' : value.toString().trim();
  return raw.length > 0 ? normalizeText(raw) : 'all';
}

function normalizeStateValue(value) {
  const raw = value == null ? '' : value.toString().trim();
  if (!raw) return '';

  const normalized = normalizeText(raw).replace(/['’]/g, '').replace(/[-]/g, ' ');
  const aliases = {
    'alger': 'alger',
    'algerie': 'alger',
    'algérie': 'alger',
    'الجزائر': 'alger',
    'adrar': 'adrar',
    'أدرار': 'adrar',
    'chlef': 'chlef',
    'الشلف': 'chlef',
    'laghouat': 'laghouat',
    'الأغواط': 'laghouat',
    'oum el bouaghi': 'oum-el-bouaghi',
    'أم البواقي': 'oum-el-bouaghi',
    'batna': 'batna',
    'باتنة': 'batna',
    'bejaia': 'bejaia',
    'béjaia': 'bejaia',
    'béjaïa': 'bejaia',
    'بجاية': 'bejaia',
    'biskra': 'biskra',
    'بسكرة': 'biskra',
    'bechar': 'bechar',
    'بشار': 'bechar',
    'blida': 'blida',
    'البليدة': 'blida',
    'bouira': 'bouira',
    'البويرة': 'bouira',
    'tamanrasset': 'tamanrasset',
    'تمنراست': 'tamanrasset',
    'tebessa': 'tebessa',
    'تبسة': 'tebessa',
    'tlemcen': 'tlemcen',
    'تلمسان': 'tlemcen',
    'tiaret': 'tiaret',
    'تيارت': 'tiaret',
    'tizi ouzou': 'tizi-ouzou',
    'تيزي وزو': 'tizi-ouzou',
    'djelfa': 'djelfa',
    'الجلفة': 'djelfa',
    'jijel': 'jijel',
    'جيجل': 'jijel',
    'setif': 'setif',
    'سطيف': 'setif',
    'saida': 'saida',
    'سعيدة': 'saida',
    'skikda': 'skikda',
    'سكيكدة': 'skikda',
    'sidi bel abbes': 'sidi-bel-abbes',
    'سيدي بلعباس': 'sidi-bel-abbes',
    'annaba': 'annaba',
    'عنابة': 'annaba',
    'guelma': 'guelma',
    'قالمة': 'guelma',
    'constantine': 'constantine',
    'قسنطينة': 'constantine',
    'medea': 'medea',
    'المدية': 'medea',
    'mostaganem': 'mostaganem',
    'مستغانم': 'mostaganem',
    'msila': 'msila',
    'المسيلة': 'msila',
    'mascara': 'mascara',
    'معسكر': 'mascara',
    'ouargla': 'ouargla',
    'ورقلة': 'ouargla',
    'oran': 'oran',
    'وهران': 'oran',
    'el bayadh': 'el-bayadh',
    'البيض': 'el-bayadh',
    'illizi': 'illizi',
    'إليزي': 'illizi',
    'bordj bou arreridj': 'bordj-bou-arreridj',
    'برج بوعريريج': 'bordj-bou-arreridj',
    'boumerdes': 'boumerdes',
    'بومرداس': 'boumerdes',
    'el tarf': 'el-tarf',
    'الطارف': 'el-tarf',
    'tindouf': 'tindouf',
    'تندوف': 'tindouf',
    'tissemsilt': 'tissemsilt',
    'تيسمسيلت': 'tissemsilt',
    'el oued': 'el-oued',
    'الوادي': 'el-oued',
    'khenchela': 'khenchela',
    'خنشلة': 'khenchela',
    'souk ahras': 'souk-ahras',
    'سوق أهراس': 'souk-ahras',
    'tipaza': 'tipaza',
    'تيبازة': 'tipaza',
    'mila': 'mila',
    'ميلة': 'mila',
    'ain defla': 'ain-defla',
    'عين الدفلى': 'ain-defla',
    'naama': 'naama',
    'النعامة': 'naama',
    'ain temouchent': 'ain-temouchent',
    'عين تموشنت': 'ain-temouchent',
    'ghardaia': 'ghardaia',
    'غرداية': 'ghardaia',
    'relizane': 'relizane',
    'غليزان': 'relizane',
    'timimoun': 'timimoun',
    'تيميمون': 'timimoun',
    'bordj badji mokhtar': 'bordj-badji-mokhtar',
    'برج باجي مختار': 'bordj-badji-mokhtar',
    'ouled djellal': 'ouled-djellal',
    'أولاد جلال': 'ouled-djellal',
    'beni abbes': 'beni-abbes',
    'بني عباس': 'beni-abbes',
    'in salah': 'in-salah',
    'عين صالح': 'in-salah',
    'in guezzam': 'in-guezzam',
    'عين قزام': 'in-guezzam',
    'touggourt': 'touggourt',
    'تقرت': 'touggourt',
    'djanet': 'djanet',
    'جانت': 'djanet',
    'el mghair': 'el-mghair',
    'المغير': 'el-mghair',
    'el meniaa': 'el-meniaa',
    'المنيعة': 'el-meniaa',
    'aflou': 'aflou',
    'آفلو': 'aflou',
    'barika': 'barika',
    'بريكة': 'barika',
    'el kantara': 'el-kantara',
    'القنطرة': 'el-kantara',
    'bir el ater': 'bir-el-ater',
    'بير العاتر': 'bir-el-ater',
    'el aricha': 'el-aricha',
    'العريشة': 'el-aricha',
    'ksar chellala': 'ksar-chellala',
    'قصر الشلالة': 'ksar-chellala',
    'ain oussara': 'ain-oussara',
    'عين وسارة': 'ain-oussara',
    'messaad': 'messaad',
    'مسعد': 'messaad',
    'ksar el boukhari': 'ksar-el-boukhari',
    'قصر البخاري': 'ksar-el-boukhari',
    'bou saada': 'bou-saada',
    'بوسعادة': 'bou-saada',
    'el abiodh sidi cheikh': 'el-abiodh-sidi-cheikh',
    'الأبيض سيدي الشيخ': 'el-abiodh-sidi-cheikh',
  };

  return aliases[normalized] || normalized;
}

module.exports = {
  normalizeText,
  normalizeStatsFilterValue,
  normalizeStateValue,
};
